---
- name: Setup Permissions on k3s rancher yaml
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Ensure /etc/rancher/k3s/k3s.yaml is readable by all
      ansible.builtin.file:
        path: /etc/rancher/k3s/k3s.yaml
        mode: 'a+r'
      become: true
