---
- name: Setup Passwordless SSH Across Nodes
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install sshpass (Debian/Ubuntu)
      apt:
        name: sshpass
        state: present
      when: ansible_os_family == "Debian"

    - name: Check for existing SSH keys
      stat:
        path: "/home/laneone/.ssh/id_rsa"
      register: ssh_key_check

    - name: Generate SSH key
      command: ssh-keygen -t rsa -b 4096 -f /home/laneone/.ssh/id_rsa -q -N ""
      args:
        creates: "/home/laneone/.ssh/id_rsa"
      when: not ssh_key_check.stat.exists

    - name: Get list of all hosts
      set_fact:
        all_hosts: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | list }}"

    - name: Copy public key to all hosts
      shell: "sshpass -p '{{ ssh_password }}' ssh-copy-id -i /home/laneone/.ssh/id_rsa.pub -o StrictHostKeyChecking=no laneone@{{ item }}"
      loop: "{{ all_hosts }}"
      ignore_errors: yes
      when: inventory_hostname != item
